### Question 1

Écrivez un programme Python pour convertir un tableau en une liste ordinaire avec les mêmes éléments.

Nous pouvons utiliser la fonction np.tolist() . 

In [2]:
import numpy as np

In [3]:
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
b=a.tolist()
print(b)

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


### Question 2 

Écrivez un programme NumPy pour calculer la somme des éléments diagonaux d'un tableau donné.

Astuce : Il existe deux méthodes possibles pour résoudre ce problème : 

Manuellement (sans fonction directe). 
Utilisation de la fonction trace 

In [16]:
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
sum_diag=np.trace(a)
print(sum_diag)

12


### Question 3

Étant donné un tableau de votre choix, obtenez toutes les valeurs supérieures à X :

Si a = [[1,2],[3,5]] et x = 2 : alors 3 et 5 sont supérieurs à 2. 

In [31]:
array = [[1,2],[3,5]]
X=2
Sup_X=[]
for valeur in array:
    for i in valeur:
        if i>X:
            Sup_X.append(i)
print("Les valeurs supérieures à", X, "sont:", Sup_X)

Les valeurs supérieures à 2 sont: [3, 5]


### Question 4

Étant donné deux tableaux, A et B ont la même forme. 

La tâche consiste à appliquer l'addition à la main : C est le nouveau tableau.  

In [33]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
C=A+B
print(C)

[[ 6  8]
 [10 12]]


### Question 5

Écrivez un programme NumPy pour soustraire la moyenne de chaque ligne d'une matrice donnée.

Astuce : utilisez la fonction moyenne 

In [34]:
Matrice=np.array([45,62],[24,14],[23,9])
moyen=np.mean(Matrice)


TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [38]:
# Créer une matrice
matrice = np.array([[1,2,3], [4,5,6], [7,8,9]])

# Calculer la moyenne de chaque ligne
moyenne = np.mean(matrice, axis=1)
moyenne
# Soustraire la moyenne de chaque ligne
matrice_soustraction = matrice - moyenne[:, np.newaxis]

print(matrice_soustraction)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
